apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis-master
spec:
  selector:
    matchLabels:
      app: redis-master
      role: master
      tier: database
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
        role: master
        tier: database
    spec:
      containers:
      - name: redis-master
        image: redis:5-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-master
    role: master
    tier: database
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis-master
